version: '3.8'

services:
  spotifetch:
    build: .
    container_name: spotifetch
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000

    volumes:
      # Persist temporary/completed downloads to host if desired
      - ./downloads:/app/downloads
